spring:
  profiles:
    include: oauth, db
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION