spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  profiles:
    include: jwt, db, aws, analysis, oauth, cors
fcm:
  properties:
    firebase-create-scoped: "https://www.googleapis.com/auth/cloud-platform"
    firebase-multicast-message-size: 500