# Generated by Django 3.2.5 on 2021-08-18 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('etype', models.CharField(max_length=31)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='JoinUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sns_id', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField()),
                ('status', models.IntegerField(blank=True, null=True)),
                ('follow_count', models.IntegerField(blank=True, default=0, null=True)),
                ('post_count', models.IntegerField(blank=True, default=0, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'join_user',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('road', models.CharField(blank=True, max_length=255, null=True)),
                ('road_code', models.CharField(blank=True, max_length=12, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('template', models.IntegerField()),
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hashtag', serialize=False, to='core.event')),
            ],
            options={
                'db_table': 'hashtag',
            },
        ),
        migrations.CreateModel(
            name='StoreImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(blank=True, max_length=255, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.store')),
            ],
            options={
                'db_table': 'store_images',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('level', models.BigIntegerField(blank=True, null=True)),
                ('used_count', models.IntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rewards', to='core.event')),
            ],
            options={
                'db_table': 'reward',
            },
        ),
        migrations.CreateModel(
            name='JoinPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sns_id', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(max_length=255)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True)),
                ('hashtags', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('create_date', models.DateTimeField()),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('private_date', models.DateTimeField(blank=True, null=True)),
                ('delete_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='core.event')),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reward', to='core.reward')),
            ],
            options={
                'db_table': 'join_post',
            },
        ),
        migrations.CreateModel(
            name='EventRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rewards', to='core.event')),
                ('rewards', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_reward_set', to='core.reward')),
            ],
            options={
                'db_table': 'event_rewards',
            },
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='core.event')),
            ],
            options={
                'db_table': 'event_images',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.store'),
        ),
        migrations.CreateModel(
            name='HashtagRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField()),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.hashtag')),
            ],
            options={
                'db_table': 'hashtag_requirements',
            },
        ),
        migrations.CreateModel(
            name='HashtagHashtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_hashtags', to='core.hashtag')),
            ],
            options={
                'db_table': 'hashtag_hashtags',
            },
        ),
    ]
