# Generated by Django 3.2.5 on 2021-08-30 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210818_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskJoinPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'task_join_post',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventimages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventrewards',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hashtaghashtags',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hashtagrequirements',
            options={},
        ),
        migrations.AlterModelOptions(
            name='joinpost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='joinuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storeimages',
            options={},
        ),
        migrations.AddField(
            model_name='taskjoinpost',
            name='join_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='join_post', to='core.joinpost'),
        ),
    ]
