# Generated by Django 3.2.5 on 2021-08-30 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210830_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('picture', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField()),
                ('modified_date', models.DateTimeField()),
                ('password', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='joinpost',
            name='reward_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joinpost',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='core.event'),
        ),
    ]
