# Generated by Django 3.2.5 on 2021-08-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210830_2145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskJoinPost',
        ),
    ]
