# Generated by Django 3.2.5 on 2021-08-30 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_taskjoinpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskJoinPost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('join_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='join_post', to='core.joinpost')),
            ],
            options={
                'db_table': 'task_join_post',
            },
        ),
    ]
