# Generated by Django 3.2.5 on 2021-09-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_taskjoinpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='image',
            new_name='image_path',
        ),
    ]
