# Generated by Django 3.2.5 on 2021-09-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_image_reward_image_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': False},
        ),
    ]
