# Generated by Django 3.2.5 on 2021-09-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_reward_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rewards', to='core.event'),
        ),
    ]
