# Generated by Django 3.2.5 on 2021-09-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_reward_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deleted',
            field=models.TextField(default='false', null=True),
        ),
        migrations.AddField(
            model_name='joinpost',
            name='deleted',
            field=models.TextField(default='false', null=True),
        ),
        migrations.AddField(
            model_name='joinuser',
            name='deleted',
            field=models.TextField(default='false', null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='deleted',
            field=models.TextField(default='false', null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='deleted',
            field=models.TextField(default='false', null=True),
        ),
    ]
