# Generated by Django 3.2.5 on 2021-09-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210907_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='joinpost',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
