# Generated by Django 3.2.5 on 2021-09-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210907_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='road_code',
        ),
        migrations.AddField(
            model_name='store',
            name='building_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
