# Generated by Django 3.2.5 on 2021-09-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210909_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventRewards',
        ),
    ]
