# Generated by Django 3.2.5 on 2021-09-24 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210924_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskjoinpost',
            name='join_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_post', to='core.joinpost'),
        ),
    ]
