# Generated by Django 3.2.5 on 2021-09-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_joinpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinpost',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
