# Generated by Django 3.2.5 on 2021-09-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_hashtaghashtags_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtaghashtags',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
