# Generated by Django 3.2.5 on 2021-09-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_hashtaghashtags_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinpost',
            name='deleted',
            field=models.BinaryField(default=False, null=True),
        ),
    ]
