# Generated by Django 3.2.5 on 2021-09-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_joinpost_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinpost',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
