# Generated by Django 3.2.5 on 2021-09-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_joinpost_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='deleted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='deleted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='deleted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='deleted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
