# Generated by Django 3.2.5 on 2021-09-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210928_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinpost',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='store',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted',
        ),
    ]
