# Generated by Django 3.2.5 on 2021-09-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210928_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinpost',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='joinuser',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
