# Generated by Django 3.2.5 on 2021-09-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210928_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='deleted',
        ),
    ]
