# Generated by Django 3.2.5 on 2021-10-01 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20210930_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventimages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hashtaghashtags',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hashtagrequirements',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storeimages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userrefreshtoken',
            options={},
        ),
    ]
