# Generated by Django 3.2.5 on 2021-10-11 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20211001_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reward_policy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='hashtaghashtags',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='building_code',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='store',
            name='country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='store',
            name='road',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='store',
            name='town',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.user'),
        ),
        migrations.AlterField(
            model_name='store',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='storeimages',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
