# Generated by Django 3.2.5 on 2021-10-11 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20211011_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exposure_count', models.IntegerField(blank=True, default=0, null=True)),
                ('participate_count', models.IntegerField(blank=True, default=0, null=True)),
                ('public_post_count', models.IntegerField(blank=True, default=0, null=True)),
                ('private_post_count', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_post_count', models.IntegerField(blank=True, default=0, null=True)),
                ('like_count', models.IntegerField(blank=True, default=0, null=True)),
                ('comment_count', models.IntegerField(blank=True, default=0, null=True)),
                ('expenditure_count', models.IntegerField(blank=True, default=0, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_event', to='core.event')),
            ],
            options={
                'db_table': 'event_report',
            },
        ),
    ]
