name: hashchecker
description: Rocketdan hashchecker project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0-nullsafety.0
  image_picker:
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.3
  fl_chart: ^0.36.2
  number_display: ^3.0.0
  http: ^0.13.3
  animated_text_kit: ^4.2.1
  flutter_naver_login: ^1.2.2
  kakao_flutter_sdk: ^0.7.0
  intl: ^0.17.0
  provider: ^5.0.0
  qr_flutter: ^4.0.0
  path_provider: ^2.0.2
  gallery_saver: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/images/create_event_step_help/
    - assets/images/event_report/
    - assets/images/sign_in/

  uses-material-design: true