class Reward:
    MAX_FOLLOW_NUMBER = 0
    MAX_MAINTAIN_NUMBER = 0
    MAX_ENGAGEMENT_NUMBER = 0
    CONSTANT_USER_FOLLOW = 0
    CONSTANT_POST_HASHTAG = 0
    CONSTANT_PREV_MAINTAIN = 0
    CONSTANT_PREV_ENGAGEMENT = 0


class InstagramReward(Reward):
    MAX_FOLLOW_NUMBER = 1000
    MAX_MAINTAIN_NUMBER = 1
    MAX_ENGAGEMENT_NUMBER = 500
    CONSTANT_USER_FOLLOW = 0.8
    CONSTANT_POST_HASHTAG = 0.8
    CONSTANT_PREV_MAINTAIN = 0.8
    CONSTANT_PREV_ENGAGEMENT = 0.8


class FacebookReward(Reward):
    MAX_FOLLOW_NUMBER = 1000
    MAX_MAINTAIN_NUMBER = 1
    MAX_ENGAGEMENT_NUMBER = 500
    CONSTANT_USER_FOLLOW = 0.8
    CONSTANT_POST_HASHTAG = 0.8
    CONSTANT_PREV_MAINTAIN = 0.8
    CONSTANT_PREV_ENGAGEMENT = 0.8
