version: "3.9"
services:
  web:
    image: nginx
    expose:
      - 80
    volumes: # nginx/conf.d 디렉토리를 복사해서 컨테이너의 /etc/nginx/conf.d에 붙여넣기
      - ./nginx/conf.d:/etc/nginx/conf.d
    container_name: nginx
    network_mode: "host"