version: '3'

services:
  server: &python
    image: moyoung/ssoda-analysis-server:v1.1
    container_name: server
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/server
    command: python manage.py runserver --settings=config.settings.development
    volumes:
      - ./server:/usr/src/app/server
    expose:
      - "8000"
  celery_worker:
    image: moyoung/ssoda-analysis-server:v1.1
    container_name: server-celery_config
    platform: linux/amd64
    <<: *python
    command: celery -A config.celery_config.development_celery worker --loglevel=info
    ports: [ ]
  nginx:
    image: nginx:latest
    container_name: server-nginx
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - server
