version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/server
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8080
    volumes:
    - ./server:/usr/src/app/server
    ports:
    - "8080:8080"
    expose:
      - "8080"