version: '3'

services:
  server: &python
    image: moyoung/ssoda-analysis-server:django
    container_name: server
#    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/server
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "8080:8080"
  celery_worker:
    image: moyoung/ssoda-analysis-server:celery
    container_name: server-celery
#    platform: linux/amd64
    <<: *python
    command: celery -A config worker --loglevel=info
    ports: [ ]
    depends_on:
      - server
#  nginx:
#    image: nginx:latest
#    container_name: server-nginx
#    platform: linux/amd64
#    ports:
#      - "80:80"
#    volumes:
#      - ./server/config/nginx:/etc/nginx/conf.d
#    depends_on:
#      - server
