version: '3'
services:
  server: &python
    image: moyoung/ssoda-analysis-server:django
    container_name: django-server
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/server
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "8080:8080"
  celery_worker:
    image: moyoung/ssoda-analysis-server:celery
    container_name: celery-worker
    platform: linux/x86_64
    <<: *python
    command: celery -A config worker --loglevel=info
    ports: [ ]
