version: '3'
services:
  server: &python
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/server
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8080
    volumes:
    - ./server:/usr/src/app/server
    ports:
    - "8080:8080"
    expose:
      - "8080"
#  rabbitmq:
#    image: rabbitmq:3.9-management
#    ports:
#      - 5672:5672
#      - 15672:15672
#    expose:
#      - "15672"
  celery_worker:
    <<: *python
    container_name: 'backend_celery_worker'
    command: celery -A config worker --loglevel=info
    ports: [ ]
