from .error_form import ErrorForm

JOIN_POST_FOUND_ERROR = ErrorForm(404, 'JOIN_POST_FOUND_ERROR', 'CLIENT_ERROR_101')
JOIN_USER_FOUND_ERROR = ErrorForm(404, 'JOIN_USER_FOUND_ERROR', 'CLIENT_ERROR_102')
EVENT_FOUND_ERROR = ErrorForm(404, 'EVENT_FOUND_ERROR', 'CLIENT_ERROR_102')
