# Generated by Django 3.2.5 on 2021-07-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('etype', models.CharField(max_length=31)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('template', models.IntegerField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'event_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'event_rewards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HashtagHashtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'hashtag_hashtags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HashtagRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField()),
            ],
            options={
                'db_table': 'hashtag_requirements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reward',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('road', models.CharField(blank=True, max_length=255, null=True)),
                ('road_code', models.CharField(blank=True, max_length=12, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'store_images',
                'managed': False,
            },
        ),
    ]
