# Generated by Django 3.2.5 on 2021-07-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('sns_id', models.IntegerField(blank=True, null=True)),
                ('url', models.CharField(max_length=255)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('comment_count', models.IntegerField(blank=True, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField()),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('private_date', models.DateTimeField(blank=True, null=True)),
                ('delete_data', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'join_post',
            },
        ),
        migrations.CreateModel(
            name='JoinUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sns_id', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField()),
                ('status', models.IntegerField(blank=True, null=True)),
                ('follow_count', models.IntegerField(blank=True, null=True)),
                ('post_count', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'join_user',
            },
        ),
    ]
