# Generated by Django 3.2.5 on 2021-07-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_eventrewards_rewards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='id',
            field=models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hashtag', serialize=False, to='api.event'),
        ),
        migrations.AlterField(
            model_name='hashtaghashtags',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_hashtags', to='api.hashtag'),
        ),
    ]
