# Generated by Django 3.2.5 on 2021-07-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_joinpost_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinpost',
            old_name='rewards_id',
            new_name='rewards_level',
        ),
    ]
