# Generated by Django 3.2.5 on 2021-08-02 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_eventrewards_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinpost',
            old_name='delete_data',
            new_name='delete_date',
        ),
        migrations.AlterField(
            model_name='eventrewards',
            name='rewards',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_reward_set', to='api.reward'),
        ),
    ]
