# Generated by Django 3.2.5 on 2021-08-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210802_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinpost',
            name='delete_date',
        ),
    ]
