# Generated by Django 3.2.5 on 2021-08-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210802_1222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventimages',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventrewards',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hashtaghashtags',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hashtagrequirements',
            options={},
        ),
        migrations.AlterModelOptions(
            name='joinpost',
            options={},
        ),
        migrations.AlterModelOptions(
            name='joinuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storeimages',
            options={},
        ),
    ]
