# Generated by Django 3.2.5 on 2021-08-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210802_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinpost',
            options={'managed': False},
        ),
    ]
