# Generated by Django 3.2.5 on 2021-08-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_joinpost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joinpost',
            options={},
        ),
    ]
