# Generated by Django 3.2.5 on 2021-08-02 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_joinpost_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinpost',
            old_name='delete_data',
            new_name='delete_date',
        ),
        migrations.AlterField(
            model_name='joinpost',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='api.event'),
        ),
    ]
