# Generated by Django 3.2.5 on 2021-08-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210802_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinpost',
            old_name='delete_date',
            new_name='delete_data',
        ),
    ]
