# Generated by Django 3.2.5 on 2021-08-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_delete_date_joinpost_delete_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinpost',
            old_name='delete_data',
            new_name='delete_date',
        ),
    ]
