# Generated by Django 3.2.5 on 2021-08-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210806_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'managed': False},
        ),
    ]
