# Generated by Django 3.2.5 on 2021-08-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_reward_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={},
        ),
    ]
