# Generated by Django 3.2.5 on 2021-08-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210806_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinpost',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reward', to='api.reward'),
        ),
    ]
