# Generated by Django 3.2.5 on 2021-08-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_joinpost_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinpost',
            name='rewards_level',
        ),
    ]
