# Generated by Django 3.2.5 on 2021-08-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_joinpost_rewards_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinpost',
            name='deleted',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='joinuser',
            name='deleted',
            field=models.TextField(default=False),
        ),
    ]
