# Generated by Django 3.2.5 on 2021-08-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210807_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinpost',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='deleted',
        ),
    ]
