# Generated by Django 3.2.5 on 2021-08-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210807_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinpost',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='joinpost',
            name='hashtags',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='joinpost',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='follow_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='joinuser',
            name='post_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
